[package]
name = "rust_mod"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
crabio = { path="../crabio" }
esp-println = { version = "0.16.1", features = ["esp32s3"] }
